//
// Created by michal on 5/27/20.
//

#ifndef SEMESTRAL_WORK_MENU_H
#define SEMESTRAL_WORK_MENU_H


#include "../graphics/Renderable.h"
#include "Button.h"

/**
 * Menu for loading or starting new game
 */
class Menu : Renderable {
public:

    /**
     * Enum representing all actions which can be returned by handleClick function
     */
    enum Action {
        NOTHING, NEW_GAME, LOAD_GAME
    };

    /**
     *
     * @param windowWidth Window width
     * @param windowHeight Window height
     * @param assets Assets for obtaining texture regions
     * @param font Font to be used for size calculations of buttons
     */
    Menu(int windowWidth, int windowHeight, const Assets *assets, TTF_Font *font);

    void render(CameraRenderer *renderer) override;

    /**
     * @brief Handle click
     * @param x X coordinate in window coordinates
     * @param y Y coordinate in window coordinates
     * @return Action generated by click Action::NOTHING if not clicked anything
     */
    Action handleClick(int x, int y);

    /**
     * @brief Method to refresh whatever load button should be shown
     */
    void refreshLoadOption();

    /**
     * @brief Make menu to handle hover at X Y
     * @param x X pixel coordinate
     * @param y Y pixel coordinate
     */
    void handleHover(int x, int y);

private:
    bool canLoadGame;

    TextureRegion *bgRegion;
    SDL_Rect targetBgRect;
    Button loadGameButton;
    Button newGameButton;
};


#endif //SEMESTRAL_WORK_MENU_H
